tablecheck/tablekit

.storybook/preview.tsx, packages/avatar/src/Avatar.stories.mdx, packages/footer/src/Footer.stories.mdx, packages/gallery/src/Gallery.stories.mdx, packages/language-selector/src/LanguageSelector.stories.tsx, packages/password-field/src/PasswordField.stories.mdx, packages/sidenav/src/Sidenav.stories.mdx, packages/tag/src/Tag.stories.mdx, packages/toggle/src/Toggle.stories.mdx
- remove '@tablecheck/tablekit-free-icon-config' import from
`preview.tsx`
- add '@tablecheck/tablekit-free-icon-config' imports to all
stories that include icons
Fixes #5
=> fix: storybook icon config

packages/input-button/src/__snapshots__/index.test.tsx.snap, packages/input-button/src/styled.ts
The checked button has solid background insted of outline
Text for all buttons is bold
Font-size is 16px (Typography.Body1)
completes #30
https://user-images.githubusercontent.com/59263605/130033903-2274c9b4-73df-4c2f-b0c2-8c6002303a1f.mov
<details>
<br />
```bash
npm install @tablecheck/tablekit-input-button@1.0.1-canary.32.14ac1f06daeb5dfe9d34a2a4d585b4ab6ab8da53.0
yarn add @tablecheck/tablekit-input-button@1.0.1-canary.32.14ac1f06daeb5dfe9d34a2a4d585b4ab6ab8da53.0
```
</details>
=> fix(tablekit-input-button): changed appearance

packages/modal-dialog/package.json, packages/modal-dialog/src/ModalDialog.stories.tsx, packages/modal-dialog/src/ModalDialog.tsx, packages/modal-dialog/src/components/AnimatedContent.tsx, packages/modal-dialog/src/styled.ts, packages/modal-dialog/src/types.ts
completes #31
<details>
<br />
```bash
npm install @tablecheck/tablekit-input-button@1.0.2-canary.33.b6e8bc0d7e1ee8f160d12db9443d05a9ca0e88cf.0
npm install @tablecheck/tablekit-modal-dialog@1.0.1-canary.33.b6e8bc0d7e1ee8f160d12db9443d05a9ca0e88cf.0
yarn add @tablecheck/tablekit-input-button@1.0.2-canary.33.b6e8bc0d7e1ee8f160d12db9443d05a9ca0e88cf.0
yarn add @tablecheck/tablekit-modal-dialog@1.0.1-canary.33.b6e8bc0d7e1ee8f160d12db9443d05a9ca0e88cf.0
```
</details>
=> feat(tablekit-modal-dialog): add maxWidth and maxHeight props

package-lock.json, package.json, packages/calendar/package.json, packages/modal-dialog/package.json, packages/modal-dialog/src/ModalDialog.stories.tsx, packages/modal-dialog/src/ModalDialog.tsx, packages/modal-dialog/src/components/ModalCloseButton.tsx, packages/modal-dialog/src/index.ts, packages/modal-dialog/src/styled.ts, packages/phone-input/package.json, packages/phone-input/src/PhoneInput.stories.tsx, packages/phone-input/src/definitions/libphonenumber-metadata.d.ts, packages/phone-input/src/definitions/react-phone-number-input.d.ts
latest version of radix-ui requires structural upgrades to modal-dialog. Latest of libphonenumber-js also has corrected types which may be breaking.
BREAKING CHANGE: modal dialog and phone-input have typescript and exports changes
<details>
<br />
```bash
npm install @tablecheck/tablekit-calendar@2.0.0-canary.52.9fc93ca5198deff624a4ca78af2a8eaeda181cd2.0
npm install @tablecheck/tablekit-modal-dialog@2.0.0-canary.52.9fc93ca5198deff624a4ca78af2a8eaeda181cd2.0
npm install @tablecheck/tablekit-phone-input@2.0.0-canary.52.9fc93ca5198deff624a4ca78af2a8eaeda181cd2.0
yarn add @tablecheck/tablekit-calendar@2.0.0-canary.52.9fc93ca5198deff624a4ca78af2a8eaeda181cd2.0
yarn add …
```
=> fix: upgrade radix-ui to 0.1 version

packages/checkbox/src/Checkbox.stories.tsx, packages/checkbox/src/Checkbox.tsx, packages/checkbox/src/styled.ts, packages/checkbox/src/types.ts, packages/radio/src/Radio.stories.tsx, packages/radio/src/Radio.tsx, packages/radio/src/styled.ts, packages/radio/src/types.ts
Referencing SUR-561 for designs in use with survey
<details>
<br />
```bash
npm install @tablecheck/tablekit-checkbox@1.1.0-canary.57.3bcd94bc8e3f0459831816f9930933b32ca97746.0
npm install @tablecheck/tablekit-radio@1.1.0-canary.57.3bcd94bc8e3f0459831816f9930933b32ca97746.0
yarn add @tablecheck/tablekit-checkbox@1.1.0-canary.57.3bcd94bc8e3f0459831816f9930933b32ca97746.0
yarn add @tablecheck/tablekit-radio@1.1.0-canary.57.3bcd94bc8e3f0459831816f9930933b32ca97746.0
```
</details>
=> feat: add large size to checkbox and radio inputs

packages/button/src/styled/themeDefinitions/outlineVariant.ts, packages/button/src/styled/themeDefinitions/subtleVariant.ts, packages/button/src/themes.ts
The `outline` and `subtle` button appearances need to use a color different than the `main` one in dark mode.
<details>
<br />
```bash
npm install @tablecheck/tablekit-alert@3.0.2-canary.70.1507385912.0
npm install @tablecheck/tablekit-banner@2.0.2-canary.70.1507385912.0
npm install @tablecheck/tablekit-button-group@2.0.2-canary.70.1507385912.0
npm install @tablecheck/tablekit-button@2.0.2-canary.70.1507385912.0
npm install @tablecheck/tablekit-calendar@3.0.2-canary.70.1507385912.0
npm install @tablecheck/tablekit-input-button@2.0.2-canary.70.1507385912.0
npm install @tablecheck/tablekit-language-selector@2.0.2-canary.70.1507385912.0
npm install …
```
=> fix: theme colors

packages/input/src/themes.ts
Completes 66
<details>
<br />
```bash
npm install @tablecheck/tablekit-calendar@3.0.4-canary.72.1528177131.0
npm install @tablecheck/tablekit-input-button@2.0.4-canary.72.1528177131.0
npm install @tablecheck/tablekit-input@2.0.3-canary.72.1528177131.0
npm install @tablecheck/tablekit-password-field@2.0.4-canary.72.1528177131.0
npm install @tablecheck/tablekit-phone-input@3.0.4-canary.72.1528177131.0
npm install @tablecheck/tablekit-radio@2.0.3-canary.72.1528177131.0
npm install @tablecheck/tablekit-select@2.0.4-canary.72.1528177131.0
npm install @tablecheck/tablekit-textarea@2.0.3-canary.72.1528177131.0
yarn add …
```
=> fix(tablekit-input): use primary2 color for icon

packages/modal-dialog/src/styled.ts
@radix-ui stopped putting z-index on portal component
so tablekit adjusted to use its own z-indices
reference: https://github.com/radix-ui/primitives/issues/760#issuecomment-952102287
<details>
<br />
```bash
npm install @tablecheck/tablekit-modal-dialog@3.0.4-canary.73.1567075960.0
yarn add @tablecheck/tablekit-modal-dialog@3.0.4-canary.73.1567075960.0
```
</details>
=> input: fix(tablekit-modal-dialog): add z-index from tablekit theme

packages/calendar/src/Weeks/styled.ts, packages/calendar/src/index.ts, packages/calendar/src/themes.ts
Completes BEXS-139
<details>
<br />
```bash
npm install @tablecheck/tablekit-calendar@3.0.5-canary.74.1577053492.0
yarn add @tablecheck/tablekit-calendar@3.0.5-canary.74.1577053492.0
```
</details>
=> fix(tablekit-calendar): add selectedTextColor to theme

packages/password-field/src/PasswordFieldStateless.tsx, packages/password-field/src/utils.ts
Completes BEXS-227 and https://github.com/tablecheck/tablekit/issues/78
<details>
<br />
```bash
npm install @tablecheck/tablekit-password-field@2.0.5-canary.77.1661826138.0
yarn add @tablecheck/tablekit-password-field@2.0.5-canary.77.1661826138.0
```
</details>
=> fix(tablekit-password-field): wrong invalid appearance

packages/icon/package.json
The maintainer has intentionally published a DoS in 1.4.1 and higher. It is recommended to lock to 1.4.0 and move to another package.
This pull request makes the following changes:
* locks colors.js to `1.4.0` by upgrading @storybook/react as per the maintainer's reaction.
* https://github.com/storybookjs/storybook/issues/17179
It relates to the following issue #s:
* Fixes #79
=> security(tablekit-icon): colors.js has embedded denial of service

packages/input/src/styled/index.ts
Fixes BEXS-244
<details>
<br />
```bash
npm install @tablecheck/tablekit-alert@3.1.1-canary.85.1754848678.0
npm install @tablecheck/tablekit-avatar@2.1.1-canary.85.1754848678.0
npm install @tablecheck/tablekit-badge@2.1.1-canary.85.1754848678.0
npm install @tablecheck/tablekit-banner@2.1.1-canary.85.1754848678.0
npm install @tablecheck/tablekit-button-group@2.1.1-canary.85.1754848678.0
npm install @tablecheck/tablekit-button@2.1.1-canary.85.1754848678.0
npm install @tablecheck/tablekit-calendar@3.1.1-canary.85.1754848678.0
npm install @tablecheck/tablekit-checkbox@2.1.1-canary.85.1754848678.0
npm install @tablecheck/tablekit-enzyme@2.1.1-canary.85.1754848678.0
npm …
```
=> fix(tablekit-input): change font size to 16px

packages/password-field/src/index.ts
<details>
<br />
```bash
npm install @tablecheck/tablekit-password-field@2.1.2-canary.86.1755505114.0
yarn add @tablecheck/tablekit-password-field@2.1.2-canary.86.1755505114.0
```
</details>
=> fix(tablekit-password-field): export stateless version

packages/modal-dialog/src/ModalDialog.stories.tsx, packages/modal-dialog/src/ModalDialog.tsx, packages/modal-dialog/src/components/AnimatedContent.tsx, packages/modal-dialog/src/types.ts
Forward on the data-testid prop so we can target a dialog correctly when there are multiple displayed.
<details>
<br />
```bash
npm install @tablecheck/tablekit-modal-dialog@3.1.2-canary.91.2062204281.0
yarn add @tablecheck/tablekit-modal-dialog@3.1.2-canary.91.2062204281.0
```
</details>
=> fix(tablekit-modal-dialog): correctly forward on data-testid prop

packages/modal-dialog/src/ModalDialog.tsx, packages/modal-dialog/src/components/AnimatedContent.tsx, packages/modal-dialog/src/styled.ts, packages/modal-dialog/src/types.ts
Passthrough the classname on the component to the modal content. this is
necessary as when triggered, the modal is not a child of the
`tablekit-modal-dialog` component, so it's not accessible to style as a
descendant
<details>
<br />
```bash
npm install @tablecheck/tablekit-modal-dialog@3.1.3-canary.92.2153021765.0
yarn add @tablecheck/tablekit-modal-dialog@3.1.3-canary.92.2153021765.0
```
</details>
=> fix(tablekit-modal-dialog): passthrough classname to modal content

packages/input/src/Label.tsx
fixes #96
<details>
<br />
```bash
npm install @tablecheck/tablekit-calendar@3.1.3-canary.97.2311629718.0
npm install @tablecheck/tablekit-input-button@2.1.3-canary.97.2311629718.0
npm install @tablecheck/tablekit-input@2.1.3-canary.97.2311629718.0
npm install @tablecheck/tablekit-password-field@2.1.4-canary.97.2311629718.0
npm install @tablecheck/tablekit-phone-input@3.1.3-canary.97.2311629718.0
npm install @tablecheck/tablekit-radio@2.1.3-canary.97.2311629718.0
npm install @tablecheck/tablekit-select@2.1.3-canary.97.2311629718.0
npm install @tablecheck/tablekit-textarea@2.1.3-canary.97.2311629718.0
yarn add @tablecheck/tablekit-calendar@3.1.3-canary.97.2311629718.0 …
```
=> fix(input): label prop can be react node or string

system/react/src/components/Radio.stories.tsx, system/react/src/components/Radio.ts, system/react/src/index.ts
Resolves https://github.com/tablecheck/tablekit/issues/106
<details>
<br />
```bash
npm install @tablecheck/tablekit-css@2.1.0-canary.122.3126475364.0
npm install @tablecheck/tablekit-react-select@2.1.0-canary.122.3126475364.0
npm install @tablecheck/tablekit-react@2.1.0-canary.122.3126475364.0
yarn add @tablecheck/tablekit-css@2.1.0-canary.122.3126475364.0
yarn add @tablecheck/tablekit-react-select@2.1.0-canary.122.3126475364.0
yarn add @tablecheck/tablekit-react@2.1.0-canary.122.3126475364.0
```
</details>
=> feat(tablekit-react): add radio component

system/react/src/components/Checkbox.ts, system/react/src/components/Checkboxes.stories.tsx
- Cursor changed to pointer/not-allowed in appropriate cases
- Do not oblige to explicitly pass to component `type="checkbox"`
<details>
<br />
```bash
npm install @tablecheck/tablekit-css@2.0.1-canary.125.3126719355.0
npm install @tablecheck/tablekit-react-select@2.0.1-canary.125.3126719355.0
npm install @tablecheck/tablekit-react@2.0.1-canary.125.3126719355.0
yarn add @tablecheck/tablekit-css@2.0.1-canary.125.3126719355.0
yarn add @tablecheck/tablekit-react-select@2.0.1-canary.125.3126719355.0
yarn add @tablecheck/tablekit-react@2.0.1-canary.125.3126719355.0
```
</details>
=> fix(tablekit-react): add cursor changes on checkbox

.storybook/preview.tsx, system/react/src/components/Badge.stories.tsx, system/react/src/components/Buttons.stories.tsx, system/react/src/components/Checkboxes.stories.tsx, system/react/src/components/InputLikeButton.stories.tsx, system/react/src/components/Inputs.stories.tsx, system/react/src/components/Radio.stories.tsx, system/react/src/components/ScrollShadow.stories.tsx, system/react/src/components/Select.stories.tsx
<details>
<br />
```bash
npm install @tablecheck/tablekit-css@2.0.1-canary.133.3172001754.0
npm install @tablecheck/tablekit-react-select@2.0.1-canary.133.3172001754.0
npm install @tablecheck/tablekit-react@2.0.1-canary.133.3172001754.0
yarn add @tablecheck/tablekit-css@2.0.1-canary.133.3172001754.0
yarn add @tablecheck/tablekit-react-select@2.0.1-canary.133.3172001754.0
yarn add @tablecheck/tablekit-react@2.0.1-canary.133.3172001754.0
```
</details>
=> fix: add header to story preview to show variant title

system/react/src/components/ButtonGroup.stories.tsx, system/react/src/components/ButtonGroup.ts, system/react/src/index.ts
Resolves #101.
<details>
<br />
```bash
npm install @tablecheck/tablekit-css@2.1.0-canary.123.3180154964.0
npm install @tablecheck/tablekit-react-select@2.1.0-canary.123.3180154964.0
npm install @tablecheck/tablekit-react@2.1.0-canary.123.3180154964.0
yarn add @tablecheck/tablekit-css@2.1.0-canary.123.3180154964.0
yarn add @tablecheck/tablekit-react-select@2.1.0-canary.123.3180154964.0
yarn add @tablecheck/tablekit-react@2.1.0-canary.123.3180154964.0
```
</details>
=> feat(tablekit-react): add button group component

.github/workflows/pull_requests.yml
To reduce the number of chromatic runs we are going to not run chromatic until the PR is marked as ready
Ref: https://github.com/reviewdog/action-eslint/issues/29#issuecomment-985939887
=> ci: skip chromatic on draft pull requests

system/react/src/components/Toggle.stories.tsx, system/react/src/components/Toggle.ts, system/react/src/index.ts
Completes #105
<details>
<br />
```bash
npm install @tablecheck/tablekit-css@2.1.0-canary.129.3428418383.0
npm install @tablecheck/tablekit-react-select@2.1.0-canary.129.3428418383.0
npm install @tablecheck/tablekit-react@2.1.0-canary.129.3428418383.0
yarn add @tablecheck/tablekit-css@2.1.0-canary.129.3428418383.0
yarn add @tablecheck/tablekit-react-select@2.1.0-canary.129.3428418383.0
yarn add @tablecheck/tablekit-react@2.1.0-canary.129.3428418383.0
```
</details>
=> feat(tablekit-react): add toggle component

system/react/src/themeVariables/constants.ts
Some IDE extensions just rely on regex matching and can’t follow the values. Changing this to just hardcode the values so that they show up correctly in integrations and we want to remove the deprecated values eventually.
<details>
<br />
```bash
npm install @tablecheck/tablekit-css@2.0.1-canary.147.3546029220.0
npm install @tablecheck/tablekit-react-select@2.0.1-canary.147.3546029220.0
npm install @tablecheck/tablekit-react@2.0.1-canary.147.3546029220.0
yarn add @tablecheck/tablekit-css@2.0.1-canary.147.3546029220.0
yarn add @tablecheck/tablekit-react-select@2.0.1-canary.147.3546029220.0
yarn add @tablecheck/tablekit-react@2.0.1-canary.147.3546029220.0
```
</details>
=> fix(tablekit-react): hardcode values for interop with IDE extensions

auditjs.json, system/react-select/src/index.tsx
Use children instead of span to preserve option props.
<details>
<br />
```bash
npm install @tablecheck/tablekit-css@2.0.1-canary.153.3848164403.0
npm install @tablecheck/tablekit-react-select@2.0.1-canary.153.3848164403.0
npm install @tablecheck/tablekit-react@2.0.1-canary.153.3848164403.0
yarn add @tablecheck/tablekit-css@2.0.1-canary.153.3848164403.0
yarn add @tablecheck/tablekit-react-select@2.0.1-canary.153.3848164403.0
yarn add @tablecheck/tablekit-react@2.0.1-canary.153.3848164403.0
```
</details>
=> fix(tablekit-react-select): fix react-select Option component

system/react/src/components/IconButton.stories.tsx, system/react/src/components/IconButton.ts, system/react/src/index.ts
Completes #102 #134
<details>
<br />
```bash
npm install @tablecheck/tablekit-css@2.1.0-canary.144.3957236757.0
npm install @tablecheck/tablekit-react-select@2.1.0-canary.144.3957236757.0
npm install @tablecheck/tablekit-react@2.1.0-canary.144.3957236757.0
yarn add @tablecheck/tablekit-css@2.1.0-canary.144.3957236757.0
yarn add @tablecheck/tablekit-react-select@2.1.0-canary.144.3957236757.0
yarn add @tablecheck/tablekit-react@2.1.0-canary.144.3957236757.0
```
</details>
=> feat(tablekit-react): add icon button component

.storybook/preview.tsx, system/react/scripts/updateFromFigma.mjs, system/react/src/components/Checkbox.stories.tsx, system/react/src/components/Checkbox.ts, system/react/src/components/CheckboxLabel.ts, system/react/src/components/Radio.stories.tsx, system/react/src/components/Radio.ts, system/react/src/index.ts, system/react/src/themeVariables/theme.ts
Utility component that would be regularly used with the checkbox component (screenshot is outdated - fixes removed the gap between focus ring and border which is also applied to radio)
<details>
<br />
```bash
npm install @tablecheck/tablekit-css@2.1.0-canary.156.4050716870.0
npm install @tablecheck/tablekit-react-fit-content-textarea@2.1.0-canary.156.4050716870.0
npm install @tablecheck/tablekit-react-select@2.1.0-canary.156.4050716870.0
npm install @tablecheck/tablekit-react@2.1.0-canary.156.4050716870.0
yarn add @tablecheck/tablekit-css@2.1.0-canary.156.4050716870.0
yarn add @tablecheck/tablekit-react-fit-content-textarea@2.1.0-canary.156.4050716870.0
yarn add …
```
=> feat(tablekit-react): add checkbox-label component

auditjs.json, system/react/src/components/Chip.stories.tsx, system/react/src/components/Chip.tsx, system/react/src/components/ChipRow.tsx, system/react/src/index.ts, system/react/src/themeVariables/constants.ts
Adding chip component and stories
resolves: #104
<details>
<br />
```bash
npm install @tablecheck/tablekit-css@2.1.0-canary.155.4101537640.0
npm install @tablecheck/tablekit-react-fit-content-textarea@2.1.0-canary.155.4101537640.0
npm install @tablecheck/tablekit-react-select@2.1.0-canary.155.4101537640.0
npm install @tablecheck/tablekit-react@2.1.0-canary.155.4101537640.0
yarn add @tablecheck/tablekit-css@2.1.0-canary.155.4101537640.0
yarn add @tablecheck/tablekit-react-fit-content-textarea@2.1.0-canary.155.4101537640.0
yarn add @tablecheck/tablekit-react-select@2.1.0-canary.155.4101537640.0
yarn add @tablecheck/tablekit-react@2.1.0-canary.155.4101537640.0
``` …
=> fix: add chip component

system/react/src/components/Badge.ts, system/react/src/themeVariables/theme.ts
No Issue
<details>
<br />
```bash
npm install @tablecheck/tablekit-css@2.1.0-canary.157.4120774475.0
npm install @tablecheck/tablekit-react-fit-content-textarea@2.1.0-canary.157.4120774475.0
npm install @tablecheck/tablekit-react-select@2.1.0-canary.157.4120774475.0
npm install @tablecheck/tablekit-react@2.1.0-canary.157.4120774475.0
yarn add @tablecheck/tablekit-css@2.1.0-canary.157.4120774475.0
yarn add @tablecheck/tablekit-react-fit-content-textarea@2.1.0-canary.157.4120774475.0
yarn add @tablecheck/tablekit-react-select@2.1.0-canary.157.4120774475.0
yarn add @tablecheck/tablekit-react@2.1.0-canary.157.4120774475.0
```
</details>
=> fix(tablekit-react): add missing variants for badge

system/react-select/src/ReactSelect.stories.tsx, system/react-select/src/index.tsx
Minor lint and a11y fixes found while investigating the issue.
Related to MOPS-808
<details>
<br />
```bash
npm install @tablecheck/tablekit-css@2.0.1-canary.158.4121536367.0
npm install @tablecheck/tablekit-react-fit-content-textarea@2.0.1-canary.158.4121536367.0
npm install @tablecheck/tablekit-react-select@2.0.1-canary.158.4121536367.0
npm install @tablecheck/tablekit-react@2.0.1-canary.158.4121536367.0
yarn add @tablecheck/tablekit-css@2.0.1-canary.158.4121536367.0
yarn add @tablecheck/tablekit-react-fit-content-textarea@2.0.1-canary.158.4121536367.0
yarn add @tablecheck/tablekit-react-select@2.0.1-canary.158.4121536367.0
yarn add …
```
=> fix(tablekit-react-select): disabled should be uninteractable

system/react/src/components/Badge.ts, system/react/src/themeVariables/theme.ts
<details>
<br />
```bash
npm install @tablecheck/tablekit-css@2.1.0-canary.160.4134968392.0
npm install @tablecheck/tablekit-react-fit-content-textarea@2.1.0-canary.160.4134968392.0
npm install @tablecheck/tablekit-react-select@2.1.0-canary.160.4134968392.0
npm install @tablecheck/tablekit-react@2.1.0-canary.160.4134968392.0
yarn add @tablecheck/tablekit-css@2.1.0-canary.160.4134968392.0
yarn add @tablecheck/tablekit-react-fit-content-textarea@2.1.0-canary.160.4134968392.0
yarn add @tablecheck/tablekit-react-select@2.1.0-canary.160.4134968392.0
yarn add @tablecheck/tablekit-react@2.1.0-canary.160.4134968392.0
```
</details>
=> feat(tablekit-react): add orange badge variant

system/react/src/components/Button.ts, system/react/src/index.ts
<details>
<br />
```bash
npm install @tablecheck/tablekit-css@2.0.1-canary.165.4351838132.0
npm install @tablecheck/tablekit-react-datepicker@2.0.1-canary.165.4351838132.0
npm install @tablecheck/tablekit-react-fit-content-textarea@2.0.1-canary.165.4351838132.0
npm install @tablecheck/tablekit-react-select@2.0.1-canary.165.4351838132.0
npm install @tablecheck/tablekit-react@2.0.1-canary.165.4351838132.0
yarn add @tablecheck/tablekit-css@2.0.1-canary.165.4351838132.0
yarn add @tablecheck/tablekit-react-datepicker@2.0.1-canary.165.4351838132.0
yarn add @tablecheck/tablekit-react-fit-content-textarea@2.0.1-canary.165.4351838132.0
yarn add …
```
=> fix(tablekit-react): export button core styles

system/react-select/src/index.tsx
Issue:
https://user-images.githubusercontent.com/19342294/226863421-0f7cc566-1231-4c01-b669-41628b41b98d.mov
<details>
<br />
```bash
npm install @tablecheck/tablekit-css@2.0.1-canary.172.4488609931.0
npm install @tablecheck/tablekit-react-datepicker@2.0.1-canary.172.4488609931.0
npm install @tablecheck/tablekit-react-fit-content-textarea@2.0.1-canary.172.4488609931.0
npm install @tablecheck/tablekit-react-select@2.0.1-canary.172.4488609931.0
npm install @tablecheck/tablekit-react@2.0.1-canary.172.4488609931.0
yarn add @tablecheck/tablekit-css@2.0.1-canary.172.4488609931.0
yarn add @tablecheck/tablekit-react-datepicker@2.0.1-canary.172.4488609931.0
yarn add …
```
=> fix(tablekit-react-select): fix text color for input

system/core/src/components/Button.ts, system/core/src/components/IconButton.ts
<details>
<br />
```bash
npm install @tablecheck/tablekit-core@2.0.1-canary.175.4665533134.0
npm install @tablecheck/tablekit-css@2.0.1-canary.175.4665533134.0
npm install @tablecheck/tablekit-react-css@2.0.1-canary.175.4665533134.0
npm install @tablecheck/tablekit-react-datepicker@2.0.1-canary.175.4665533134.0
npm install @tablecheck/tablekit-react-fit-content-textarea@2.0.1-canary.175.4665533134.0
npm install @tablecheck/tablekit-react-select@2.0.1-canary.175.4665533134.0
npm install @tablecheck/tablekit-react@2.0.1-canary.175.4665533134.0
yarn add @tablecheck/tablekit-core@2.0.1-canary.175.4665533134.0
yarn add @tablecheck/tablekit-css@2.0.1-canary.175.4665533134.0 …
```
=> fix: button disabled styles

system/core/src/components/Button.ts
Before:
After:
<details>
<br />
```bash
npm install @tablecheck/tablekit-core@2.0.1-canary.176.4686200033.0
npm install @tablecheck/tablekit-css@2.0.1-canary.176.4686200033.0
npm install @tablecheck/tablekit-react-css@2.0.1-canary.176.4686200033.0
npm install @tablecheck/tablekit-react-datepicker@2.0.1-canary.176.4686200033.0
npm install @tablecheck/tablekit-react-fit-content-textarea@2.0.1-canary.176.4686200033.0
npm install @tablecheck/tablekit-react-select@2.0.1-canary.176.4686200033.0
npm install @tablecheck/tablekit-react@2.0.1-canary.176.4686200033.0
yarn add @tablecheck/tablekit-core@2.0.1-canary.176.4686200033.0
yarn add …
```
=> fix: button styling for stretched state

system/react-select/src/index.tsx, system/stories/src/ReactSelect.stories.tsx
Add possibility to display selected values vertically by passing "useVerticalMultiValues" prop.
<details>
<br />
```bash
npm install @tablecheck/tablekit-core@2.0.1-canary.177.4727224744.0
npm install @tablecheck/tablekit-css@2.0.1-canary.177.4727224744.0
npm install @tablecheck/tablekit-react-css@2.0.1-canary.177.4727224744.0
npm install @tablecheck/tablekit-react-datepicker@2.0.1-canary.177.4727224744.0
npm install @tablecheck/tablekit-react-fit-content-textarea@2.0.1-canary.177.4727224744.0
npm install @tablecheck/tablekit-react-select@2.0.1-canary.177.4727224744.0
npm install @tablecheck/tablekit-react@2.0.1-canary.177.4727224744.0
yarn add …
```
=> feat: add vertical multi values variant

system/react-select/src/index.tsx
If select is not searchable input is not wrapped with div tag.
<details>
<br />
```bash
npm install @tablecheck/tablekit-react-select@2.0.1-canary.178.4820996238.0
yarn add @tablecheck/tablekit-react-select@2.0.1-canary.178.4820996238.0
```
</details>
=> fix: react select styles for non-searchable variant

.github/workflows/pull_requests.yml
According to https://github.com/actions/checkout/issues/551#issuecomment-1113089390 this should fix the issue in our recent contributions.
<details>
<br />
```bash
npm install @tablecheck/tablekit-core@2.0.1-canary.181.4910889090.0
npm install @tablecheck/tablekit-css@2.0.1-canary.181.4910889090.0
npm install @tablecheck/tablekit-react-css@2.0.1-canary.181.4910889090.0
npm install @tablecheck/tablekit-react-datepicker@2.0.1-canary.181.4910889090.0
npm install @tablecheck/tablekit-react-fit-content-textarea@2.0.1-canary.181.4910889090.0
npm install @tablecheck/tablekit-react-select@2.0.1-canary.181.4910889090.0
npm install …
```
=> ci: allow pull_requests pipeline to run on forks

system/core/src/components/MenuItem.ts, system/core/src/components/MenuList.ts
fix for #162 
Removed "'& > li > *': " selector styles from MenuList.ts file and added those styles under baseStyleObject in MenuItem.ts
=> fix: MenuItem override styles by classname

system/core/src/components/Button.ts, system/core/src/components/IconButton.ts, system/core/src/components/Spinner.ts, system/stories/src/Spinner.stories.tsx
Didn't take a screenshot before but basically it was invisible due to no background-color for the mask.
<details>
<br />
```bash
npm install @tablecheck/tablekit-core@2.0.1-canary.184.5010581003.0
npm install @tablecheck/tablekit-css@2.0.1-canary.184.5010581003.0
npm install @tablecheck/tablekit-react-css@2.0.1-canary.184.5010581003.0
npm install @tablecheck/tablekit-react-datepicker@2.0.1-canary.184.5010581003.0
npm install @tablecheck/tablekit-react-fit-content-textarea@2.0.1-canary.184.5010581003.0
npm install @tablecheck/tablekit-react-select@2.0.1-canary.184.5010581003.0
npm install @tablecheck/tablekit-react@2.0.1-canary.184.5010581003.0
yarn add …
```
=> fix: standalone spinner styling bugs

system/core/src/components/IconButton.ts, system/core/src/components/Select.ts, system/core/src/components/Toggle.ts
No ticket
<details>
<br />
```bash
npm install @tablecheck/tablekit-core@2.0.1-canary.185.5118342175.0
npm install @tablecheck/tablekit-css@2.0.1-canary.185.5118342175.0
npm install @tablecheck/tablekit-react-css@2.0.1-canary.185.5118342175.0
npm install @tablecheck/tablekit-react-datepicker@2.0.1-canary.185.5118342175.0
npm install @tablecheck/tablekit-react-fit-content-textarea@2.0.1-canary.185.5118342175.0
npm install @tablecheck/tablekit-react-select@2.0.1-canary.185.5118342175.0
npm install @tablecheck/tablekit-react@2.0.1-canary.185.5118342175.0
yarn add @tablecheck/tablekit-core@2.0.1-canary.185.5118342175.0
yarn add …
```
=> fix: match types and css data-* selectors

system/core/src/components/InputAlert.ts, system/react/src/index.ts, system/react/src/structuredComponents/InputStructure.tsx, system/stories/src/InputAlert.stories.tsx, system/stories/src/InputStructure.stories.tsx
Ticket: MOPS-1152
1. Change `color` of `InputAlert` from `--error` to `--error-text` for better contrast in dark mode
2. Create stories for `InputAlert` and `InputStructure`
=> feat(tablekit-core): change color for error in `InputAlert`, add stories for `InputStructure` and `InputAlert`

system/core/src/components/InputAlert.ts
1. Set color warning text for `InputAlert` from `--warning` to `--warning-text`
<details>
<br />
```bash
npm install @tablecheck/tablekit-core@2.0.1-canary.187.5285271417.0
npm install @tablecheck/tablekit-css@2.0.1-canary.187.5285271417.0
npm install @tablecheck/tablekit-react-css@2.0.1-canary.187.5285271417.0
npm install @tablecheck/tablekit-react-datepicker@2.0.1-canary.187.5285271417.0
npm install @tablecheck/tablekit-react-fit-content-textarea@2.0.1-canary.187.5285271417.0
npm install @tablecheck/tablekit-react-select@2.0.1-canary.187.5285271417.0
npm install @tablecheck/tablekit-react@2.0.1-canary.187.5285271417.0
yarn add …
```
=> fix(tablekit-core): update warn text for `InputAlert`

system/css/src/build.ts
The minifier was getting passed an empty array due to there being a `allFiles` global var and a class property. This meant that the build didn't output any minified (`.min.css`) files.
<details>
<br />
```bash
npm install @tablecheck/tablekit-core@2.0.1-canary.188.5307140042.0
npm install @tablecheck/tablekit-css@2.0.1-canary.188.5307140042.0
npm install @tablecheck/tablekit-react-css@2.0.1-canary.188.5307140042.0
npm install @tablecheck/tablekit-react-datepicker@2.0.1-canary.188.5307140042.0
npm install @tablecheck/tablekit-react-fit-content-textarea@2.0.1-canary.188.5307140042.0
npm install @tablecheck/tablekit-react-select@2.0.1-canary.188.5307140042.0
npm install …
```
=> fix: correct scoping for allFiles to pass to minifier

auditjs.json, system/core/src/components/Alert.ts, system/core/src/components/InputAlert.ts, system/core/src/index.ts, system/react-css/src/index.ts, system/react-css/src/structuredComponents/Alert.tsx, system/react/src/index.ts, system/react/src/structuredComponents/Alert.tsx, system/stories/.storybook/preview.tsx, system/stories/src/Alert.stories.tsx, system/stories/src/Menu.stories.tsx
Add base alert and fix input alert
close #108
<details>
<br />
```bash
npm install @tablecheck/tablekit-core@2.1.0-canary.189.5516015831.0
npm install @tablecheck/tablekit-css@2.1.0-canary.189.5516015831.0
npm install @tablecheck/tablekit-react-css@2.1.0-canary.189.5516015831.0
npm install @tablecheck/tablekit-react-datepicker@2.1.0-canary.189.5516015831.0
npm install @tablecheck/tablekit-react-fit-content-textarea@2.1.0-canary.189.5516015831.0
npm install @tablecheck/tablekit-react-select@2.1.0-canary.189.5516015831.0
npm install @tablecheck/tablekit-react@2.1.0-canary.189.5516015831.0
yarn add @tablecheck/tablekit-core@2.1.0-canary.189.5516015831.0
yarn add …
```
=> fix: update alerts

system/core/src/components/Alert.ts, system/react-css/src/structuredComponents/Alert.tsx, system/react/src/structuredComponents/Alert.tsx, system/stories/.storybook/preview.tsx, system/stories/src/Alert.stories.tsx
No ticket
<details>
<br />
```bash
npm install @tablecheck/tablekit-core@2.0.1-canary.190.5528090547.0
npm install @tablecheck/tablekit-css@2.0.1-canary.190.5528090547.0
npm install @tablecheck/tablekit-react-css@2.0.1-canary.190.5528090547.0
npm install @tablecheck/tablekit-react-datepicker@2.0.1-canary.190.5528090547.0
npm install @tablecheck/tablekit-react-fit-content-textarea@2.0.1-canary.190.5528090547.0
npm install @tablecheck/tablekit-react-select@2.0.1-canary.190.5528090547.0
npm install @tablecheck/tablekit-react@2.0.1-canary.190.5528090547.0
yarn add @tablecheck/tablekit-core@2.0.1-canary.190.5528090547.0
yarn add …
```
=> fix: add missing alert layouts and remove irrelevant type

system/core/src/components/IconButton.ts, system/core/src/components/TabButton.ts
closes #193
<details>
<br />
```bash
npm install @tablecheck/tablekit-core@2.0.1-canary.194.5528401108.0
npm install @tablecheck/tablekit-css@2.0.1-canary.194.5528401108.0
npm install @tablecheck/tablekit-react-css@2.0.1-canary.194.5528401108.0
npm install @tablecheck/tablekit-react-datepicker@2.0.1-canary.194.5528401108.0
npm install @tablecheck/tablekit-react-fit-content-textarea@2.0.1-canary.194.5528401108.0
npm install @tablecheck/tablekit-react-select@2.0.1-canary.194.5528401108.0
npm install @tablecheck/tablekit-react@2.0.1-canary.194.5528401108.0
yarn add @tablecheck/tablekit-core@2.0.1-canary.194.5528401108.0
yarn add …
```
=> fix: remove medium font-weight references

system/core/src/components/MenuItem.ts, system/stories/src/Menu.stories.tsx
* Added `data-variant` prop to `MenuItem`
<details>
<br />
```bash
npm install @tablecheck/tablekit-core@2.1.0-canary.196.5758751898.0
npm install @tablecheck/tablekit-css@2.1.0-canary.196.5758751898.0
npm install @tablecheck/tablekit-react-css@2.1.0-canary.196.5758751898.0
npm install @tablecheck/tablekit-react-datepicker@2.1.0-canary.196.5758751898.0
npm install @tablecheck/tablekit-react-fit-content-textarea@2.1.0-canary.196.5758751898.0
npm install @tablecheck/tablekit-react-select@2.1.0-canary.196.5758751898.0
npm install @tablecheck/tablekit-react@2.1.0-canary.196.5758751898.0
yarn add @tablecheck/tablekit-core@2.1.0-canary.196.5758751898.0
yarn add …
```
=> feat(tablekit-core): add `data-variant` as prop for `MenuItem`

system/core/src/components/Button.ts, system/core/src/components/IconButton.ts
Found this inconsistency when putting two buttons next to each other. Padding are "magical numbers" because of 1px border width.
<details>
<br />
```bash
npm install @tablecheck/tablekit-core@2.0.1-canary.197.5854331170.0
npm install @tablecheck/tablekit-css@2.0.1-canary.197.5854331170.0
npm install @tablecheck/tablekit-react-css@2.0.1-canary.197.5854331170.0
npm install @tablecheck/tablekit-react-datepicker@2.0.1-canary.197.5854331170.0
npm install @tablecheck/tablekit-react-fit-content-textarea@2.0.1-canary.197.5854331170.0
npm install @tablecheck/tablekit-react-select@2.0.1-canary.197.5854331170.0
npm install @tablecheck/tablekit-react@2.0.1-canary.197.5854331170.0 …
```
=> fix: make button and icon button consistently sized

system/core/src/components/Tabs.ts
No ticket
<details>
<br />
```bash
npm install @tablecheck/tablekit-core@2.0.1-canary.198.5874799501.0
npm install @tablecheck/tablekit-css@2.0.1-canary.198.5874799501.0
npm install @tablecheck/tablekit-react-css@2.0.1-canary.198.5874799501.0
npm install @tablecheck/tablekit-react-datepicker@2.0.1-canary.198.5874799501.0
npm install @tablecheck/tablekit-react-fit-content-textarea@2.0.1-canary.198.5874799501.0
npm install @tablecheck/tablekit-react-select@2.0.1-canary.198.5874799501.0
npm install @tablecheck/tablekit-react@2.0.1-canary.198.5874799501.0
yarn add @tablecheck/tablekit-core@2.0.1-canary.198.5874799501.0
yarn add …
```
=> fix: add wrap option to tabs and reduce gap to 8px

system/core/src/components/MenuItem.ts, system/core/src/utils/resetCss.ts, system/stories/src/Menu.stories.tsx
Closes #141
<details>
<br />
```bash
npm install @tablecheck/tablekit-core@2.1.0-canary.201.5888231482.0
npm install @tablecheck/tablekit-css@2.1.0-canary.201.5888231482.0
npm install @tablecheck/tablekit-react-css@2.1.0-canary.201.5888231482.0
npm install @tablecheck/tablekit-react-datepicker@2.1.0-canary.201.5888231482.0
npm install @tablecheck/tablekit-react-fit-content-textarea@2.1.0-canary.201.5888231482.0
npm install @tablecheck/tablekit-react-select@2.1.0-canary.201.5888231482.0
npm install @tablecheck/tablekit-react@2.1.0-canary.201.5888231482.0
yarn add @tablecheck/tablekit-core@2.1.0-canary.201.5888231482.0
yarn add …
```
=> feat: add default anchor styling

system/core/src/components/Button.ts, system/core/src/components/IconButton.ts, system/core/src/components/MenuItem.ts, system/core/src/utils/resetCss.ts, system/stories/src/Menu.stories.tsx
If link doesn’t have a href (ie `:link` doesn’t match) we need to make sure it’s disabled display even when hovered. Also added a check to not apply when being used as a "button".
<details>
<br />
```bash
npm install @tablecheck/tablekit-core@2.0.1-canary.202.5898153025.0
npm install @tablecheck/tablekit-css@2.0.1-canary.202.5898153025.0
npm install @tablecheck/tablekit-react-css@2.0.1-canary.202.5898153025.0
npm install @tablecheck/tablekit-react-datepicker@2.0.1-canary.202.5898153025.0
npm install @tablecheck/tablekit-react-fit-content-textarea@2.0.1-canary.202.5898153025.0
npm install @tablecheck/tablekit-react-select@2.0.1-canary.202.5898153025.0
npm install …
```
=> fix: link hover/active/visited only apply when link

system/.eslintrc.js, system/core/src/components/Anchor.ts, system/core/src/index.ts, system/core/src/utils/resetCss.ts, system/react-css/scripts/generateComponents.mjs, system/react-css/src/components/Anchor.tsx, system/react-css/src/index.ts, system/react/scripts/generateComponents.mjs, system/react/src/components/Anchor.tsx, system/react/src/index.ts, system/stories/src/Anchor.stories.tsx
Globally applying styles to the a tag caused a large amount of regression problems and couldn’t be modified to work easier than we could create a new component for it. Called this component `Anchor` as `a` is an `anchor tag` and `Link` conflicts with React-Router and other routing libraries.
<details>
<br />
```bash
npm install @tablecheck/tablekit-core@2.0.1-canary.203.5900611528.0
npm install @tablecheck/tablekit-css@2.0.1-canary.203.5900611528.0
npm install @tablecheck/tablekit-react-css@2.0.1-canary.203.5900611528.0
npm install @tablecheck/tablekit-react-datepicker@2.0.1-canary.203.5900611528.0
npm install …
```
=> fix: move link to Anchor component

system/core/src/components/ChildAnchors.ts, system/core/src/index.ts, system/react-css/src/components/ChildAnchors.tsx, system/react-css/src/index.ts, system/react/src/components/ChildAnchors.tsx, system/react/src/index.ts, system/stories/src/ChildAnchors.stories.tsx
This would be used in places we have "external" or "user" content as pictured below.
<details>
<br />
```bash
npm install @tablecheck/tablekit-core@2.1.0-canary.204.5921542409.0
npm install @tablecheck/tablekit-css@2.1.0-canary.204.5921542409.0
npm install @tablecheck/tablekit-react-css@2.1.0-canary.204.5921542409.0
npm install @tablecheck/tablekit-react-datepicker@2.1.0-canary.204.5921542409.0
npm install @tablecheck/tablekit-react-fit-content-textarea@2.1.0-canary.204.5921542409.0
npm install @tablecheck/tablekit-react-select@2.1.0-canary.204.5921542409.0
npm install @tablecheck/tablekit-react@2.1.0-canary.204.5921542409.0
yarn add …
```
=> feat: add component to auto apply anchor styling to children

system/core/src/components/Button.ts, system/core/src/components/IconButton.ts
No Ticket
Removes the need for this kind of wrapper;
```ts
export const AnchorButton = styled(Button.withComponent('a'))`
text-decoration: none;
`;
```
<details>
<br />
```bash
npm install @tablecheck/tablekit-core@2.0.1-canary.205.6142799525.0
npm install @tablecheck/tablekit-css@2.0.1-canary.205.6142799525.0
npm install @tablecheck/tablekit-react-css@2.0.1-canary.205.6142799525.0
npm install @tablecheck/tablekit-react-datepicker@2.0.1-canary.205.6142799525.0
npm install @tablecheck/tablekit-react-fit-content-textarea@2.0.1-canary.205.6142799525.0
npm install @tablecheck/tablekit-react-select@2.0.1-canary.205.6142799525.0
npm install …
```
=> fix: prevent text-decoration when using a button as a link

system/core/src/components/Button.ts, system/core/src/components/IconButton.ts
Implement #191 
1. Implement danger for `Button`
2. Remove danger from `danger` from `IconButton` (since button style is spread in IconButton)
<details>
<br />
```bash
npm install @tablecheck/tablekit-core@2.1.0-canary.206.6243019782.0
npm install @tablecheck/tablekit-css@2.1.0-canary.206.6243019782.0
npm install @tablecheck/tablekit-react-css@2.1.0-canary.206.6243019782.0
npm install @tablecheck/tablekit-react-datepicker@2.1.0-canary.206.6243019782.0
npm install @tablecheck/tablekit-react-fit-content-textarea@2.1.0-canary.206.6243019782.0
npm install @tablecheck/tablekit-react-select@2.1.0-canary.206.6243019782.0
npm install …
```
=> feat: implement danger variant for button

auditjs.json, system/react-select/src/index.tsx
Due to how our CSS works when using `react-select`, we have a styling that gets applied with priority over the `max-height` set by `maxMenuHeight`. This PR sticks `!important` on that CSS so it wins out.
A use case with `maxMenuHeight` prop set to `600`:
Before:
After:
<details>
<br />
```bash
npm install @tablecheck/tablekit-core@2.0.1-canary.209.6479917599.0
npm install @tablecheck/tablekit-css@2.0.1-canary.209.6479917599.0
npm install @tablecheck/tablekit-react-css@2.0.1-canary.209.6479917599.0
npm install @tablecheck/tablekit-react-datepicker@2.0.1-canary.209.6479917599.0
npm install @tablecheck/tablekit-react-fit-content-textarea@2.0.1-canary.209.6479917599.0
npm …
```
=> fix(tablekit-react-select): allow maxMenuHeight to work

system/core/src/components/Badge.ts, system/stories/src/Badge.stories.tsx
No ticket. Updates from figma
<details>
<br />
```bash
npm install @tablecheck/tablekit-core@2.1.0-canary.210.6491216729.0
npm install @tablecheck/tablekit-css@2.1.0-canary.210.6491216729.0
npm install @tablecheck/tablekit-react-css@2.1.0-canary.210.6491216729.0
npm install @tablecheck/tablekit-react-datepicker@2.1.0-canary.210.6491216729.0
npm install @tablecheck/tablekit-react-fit-content-textarea@2.1.0-canary.210.6491216729.0
npm install @tablecheck/tablekit-react-select@2.1.0-canary.210.6491216729.0
npm install @tablecheck/tablekit-react@2.1.0-canary.210.6491216729.0
yarn add @tablecheck/tablekit-core@2.1.0-canary.210.6491216729.0
yarn add …
```
=> feat: add new Badge sizes

auditjs.json, package-lock.json, system/core/scripts/updateFromFigma.mjs, system/core/src/components/Select.ts, system/core/src/themeVariables/theme.ts, system/react-css/src/structuredComponents/ThemeProvider.tsx, system/react/src/structuredComponents/ThemeProvider.tsx
Adds `system` alongside `light` and `dark` and defaults to `system` if parameter not passed.
<details>
<br />
```bash
npm install @tablecheck/tablekit-core@2.1.0-canary.211.6569801896.0
npm install @tablecheck/tablekit-css@2.1.0-canary.211.6569801896.0
npm install @tablecheck/tablekit-react-css@2.1.0-canary.211.6569801896.0
npm install @tablecheck/tablekit-react-datepicker@2.1.0-canary.211.6569801896.0
npm install @tablecheck/tablekit-react-fit-content-textarea@2.1.0-canary.211.6569801896.0
npm install @tablecheck/tablekit-react-select@2.1.0-canary.211.6569801896.0
npm install @tablecheck/tablekit-react@2.1.0-canary.211.6569801896.0
yarn add …
```
=> feat: add system theme mode and `themedCss` util

auditjs.json, system/core/src/components/Alert.ts, system/stories/src/Alert.stories.tsx
No ticket.
The issue example:
<details>
<br />
```bash
npm install @tablecheck/tablekit-core@2.0.1-canary.212.6726828953.0
npm install @tablecheck/tablekit-css@2.0.1-canary.212.6726828953.0
npm install @tablecheck/tablekit-react-css@2.0.1-canary.212.6726828953.0
npm install @tablecheck/tablekit-react-datepicker@2.0.1-canary.212.6726828953.0
npm install @tablecheck/tablekit-react-fit-content-textarea@2.0.1-canary.212.6726828953.0
npm install @tablecheck/tablekit-react-select@2.0.1-canary.212.6726828953.0
npm install @tablecheck/tablekit-react@2.0.1-canary.212.6726828953.0
yarn add @tablecheck/tablekit-core@2.0.1-canary.212.6726828953.0
yarn add …
```
=> fix: alert styles

system/react-datepicker/src/Header/MonthArrowButtons.tsx, system/react-datepicker/src/Weeks/Day.tsx
To prevent accidental submission of forms, found this in one of our tests where clicking a date would submit the parent form.
<details>
<br />
```bash
npm install @tablecheck/tablekit-core@2.0.1-canary.213.6976450883.0
npm install @tablecheck/tablekit-css@2.0.1-canary.213.6976450883.0
npm install @tablecheck/tablekit-react-css@2.0.1-canary.213.6976450883.0
npm install @tablecheck/tablekit-react-datepicker@2.0.1-canary.213.6976450883.0
npm install @tablecheck/tablekit-react-fit-content-textarea@2.0.1-canary.213.6976450883.0
npm install @tablecheck/tablekit-react-select@2.0.1-canary.213.6976450883.0
npm install @tablecheck/tablekit-react@2.0.1-canary.213.6976450883.0 …
```
=> fix: date picker buttons need type=“button”

system/core/src/components/InputWithIcons.ts, system/react-select/src/index.tsx
Apply correct text color for input and select when element is disabled.
Issues: 
<details>
<br />
```bash
npm install @tablecheck/tablekit-core@2.0.1-canary.220.8793955100.0
npm install @tablecheck/tablekit-css@2.0.1-canary.220.8793955100.0
npm install @tablecheck/tablekit-react-css@2.0.1-canary.220.8793955100.0
npm install @tablecheck/tablekit-react-datepicker@2.0.1-canary.220.8793955100.0
npm install @tablecheck/tablekit-react-fit-content-textarea@2.0.1-canary.220.8793955100.0
npm install @tablecheck/tablekit-react-select@2.0.1-canary.220.8793955100.0
npm install @tablecheck/tablekit-react@2.0.1-canary.220.8793955100.0
yarn add …
```
=> fix: use disabled text color in input and select

system/react-datepicker/src/Root.tsx
Do not subtract 1 day for min date prop.
Resolves VCHR-267.
<details>
<br />
```bash
npm install @tablecheck/tablekit-core@2.0.1-canary.224.9259474154.0
npm install @tablecheck/tablekit-css@2.0.1-canary.224.9259474154.0
npm install @tablecheck/tablekit-react-css@2.0.1-canary.224.9259474154.0
npm install @tablecheck/tablekit-react-datepicker@2.0.1-canary.224.9259474154.0
npm install @tablecheck/tablekit-react-select@2.0.1-canary.224.9259474154.0
npm install @tablecheck/tablekit-react@2.0.1-canary.224.9259474154.0
yarn add @tablecheck/tablekit-core@2.0.1-canary.224.9259474154.0
yarn add @tablecheck/tablekit-css@2.0.1-canary.224.9259474154.0
yarn add …
```
=> fix: datepicker min date

system/core/src/components/IconButton.ts, system/core/src/components/InputWithIcons.ts, system/core/src/components/InputWithPrefix.ts, system/core/src/components/TextAreaWithIcons.ts, system/core/src/components/TextAreaWithPrefix.ts, system/stories/src/IconButton.stories.tsx
Fixes padding offsets and inconsistencies
<details>
<br />
```bash
npm install @tablecheck/tablekit-core@3.0.3-canary.227.9296512980.0
npm install @tablecheck/tablekit-css@3.0.3-canary.227.9296512980.0
npm install @tablecheck/tablekit-react@3.0.3-canary.227.9296512980.0
npm install @tablecheck/tablekit-react-css@3.0.3-canary.227.9296512980.0
npm install @tablecheck/tablekit-react-datepicker@3.0.3-canary.227.9296512980.0
npm install @tablecheck/tablekit-react-select@3.0.3-canary.227.9296512980.0
yarn add @tablecheck/tablekit-core@3.0.3-canary.227.9296512980.0
yarn add @tablecheck/tablekit-css@3.0.3-canary.227.9296512980.0
yarn add …
```
=> fix: icon button in input-append mode

system/core/src/components/InputCore.ts, system/react-css/src/config.tsx, system/react-css/src/structuredComponents/Input.tsx, system/react/src/config.tsx, system/react/src/structuredComponents/Input.tsx, system/stories/src/Input.stories.tsx
`disabled` is on input props but the “Input Wrapper” type elements need to set `data-variant: ‘disabled’`.
See https://github.com/tablecheck/settings-frontend/pull/878#issuecomment-2140054836
<details>
<br />
```bash
npm install @tablecheck/tablekit-core@3.0.4-canary.229.9311772607.0
npm install @tablecheck/tablekit-css@3.0.4-canary.229.9311772607.0
npm install @tablecheck/tablekit-react@3.0.4-canary.229.9311772607.0
npm install @tablecheck/tablekit-react-css@3.0.4-canary.229.9311772607.0
npm install @tablecheck/tablekit-react-datepicker@3.0.4-canary.229.9311772607.0
npm install @tablecheck/tablekit-react-select@3.0.4-canary.229.9311772607.0
yarn add …
```
=> fix: disabled prop on Input component is not being respected

system/core/src/components/FormBanner.ts, system/core/src/index.ts, system/react-css/src/config.tsx, system/react-css/src/index.ts, system/react-css/src/structuredComponents/FormBanner.tsx, system/react/src/config.tsx, system/react/src/index.ts, system/react/src/structuredComponents/FormBanner.tsx, system/stories/src/FormBanner.stories.tsx
Figma: https://www.figma.com/design/W3hxWj6VZydNaNGJSGxRsV/TableKit-Components-(3.0)?node-id=7315-46545&m=dev
<details>
<br />
```bash
npm install @tablecheck/tablekit-core@3.0.5-canary.228.9316166211.0
npm install @tablecheck/tablekit-css@3.0.5-canary.228.9316166211.0
npm install @tablecheck/tablekit-react@3.0.5-canary.228.9316166211.0
npm install @tablecheck/tablekit-react-css@3.0.5-canary.228.9316166211.0
npm install @tablecheck/tablekit-react-datepicker@3.0.5-canary.228.9316166211.0
npm install @tablecheck/tablekit-react-select@3.0.5-canary.228.9316166211.0
yarn add @tablecheck/tablekit-core@3.0.5-canary.228.9316166211.0
yarn add …
```
=> feat: add form banner component

system/react-css/src/structuredComponents/Input.tsx, system/react/src/structuredComponents/Input.tsx
Tests generally rely on the disabled attribute
<details>
<br />
```bash
npm install @tablecheck/tablekit-core@3.0.6-canary.230.9342967722.0
npm install @tablecheck/tablekit-css@3.0.6-canary.230.9342967722.0
npm install @tablecheck/tablekit-react@3.0.6-canary.230.9342967722.0
npm install @tablecheck/tablekit-react-css@3.0.6-canary.230.9342967722.0
npm install @tablecheck/tablekit-react-datepicker@3.0.6-canary.230.9342967722.0
npm install @tablecheck/tablekit-react-select@3.0.6-canary.230.9342967722.0
yarn add @tablecheck/tablekit-core@3.0.6-canary.230.9342967722.0
yarn add @tablecheck/tablekit-css@3.0.6-canary.230.9342967722.0
yarn add …
```
=> fix: input should set `disabled` attribute

system/react-css/src/structuredComponents/FormBanner.tsx, system/react/src/structuredComponents/FormBanner.tsx
<details>
<br />
```bash
npm install @tablecheck/tablekit-core@3.0.6-canary.231.9348854629.0
npm install @tablecheck/tablekit-css@3.0.6-canary.231.9348854629.0
npm install @tablecheck/tablekit-react@3.0.7-canary.231.9348854629.0
npm install @tablecheck/tablekit-react-css@3.0.7-canary.231.9348854629.0
npm install @tablecheck/tablekit-react-datepicker@3.0.7-canary.231.9348854629.0
npm install @tablecheck/tablekit-react-select@3.0.7-canary.231.9348854629.0
yarn add @tablecheck/tablekit-core@3.0.6-canary.231.9348854629.0
yarn add @tablecheck/tablekit-css@3.0.6-canary.231.9348854629.0
yarn add @tablecheck/tablekit-react@3.0.7-canary.231.9348854629.0
yarn add …
```
=> fix: form banner default icon size

localNodeModulesSync.mjs, system/react-css/src/structuredComponents/TextArea.tsx, system/react/src/structuredComponents/TextArea.tsx
Fixes a crash on SSR
<details>
<br />
```bash
npm install @tablecheck/tablekit-core@3.0.6-canary.232.9375681919.0
npm install @tablecheck/tablekit-css@3.0.6-canary.232.9375681919.0
npm install @tablecheck/tablekit-react@3.0.8-canary.232.9375681919.0
npm install @tablecheck/tablekit-react-css@3.0.8-canary.232.9375681919.0
npm install @tablecheck/tablekit-react-datepicker@3.0.8-canary.232.9375681919.0
npm install @tablecheck/tablekit-react-select@3.0.8-canary.232.9375681919.0
yarn add @tablecheck/tablekit-core@3.0.6-canary.232.9375681919.0
yarn add @tablecheck/tablekit-css@3.0.6-canary.232.9375681919.0
yarn add @tablecheck/tablekit-react@3.0.8-canary.232.9375681919.0 …
```
=> fix: window is not defined in SSR and throws error

system/core/src/components/MenuItem.ts, system/core/src/components/MenuList.ts, system/core/src/themeVariables/theme.ts
Requested by Tom
<details>
<br />
```bash
npm install @tablecheck/tablekit-core@3.0.6-canary.234.9398313390.0
npm install @tablecheck/tablekit-css@3.0.6-canary.234.9398313390.0
npm install @tablecheck/tablekit-react@3.0.10-canary.234.9398313390.0
npm install @tablecheck/tablekit-react-css@3.0.9-canary.234.9398313390.0
npm install @tablecheck/tablekit-react-datepicker@3.0.10-canary.234.9398313390.0
npm install @tablecheck/tablekit-react-select@3.0.10-canary.234.9398313390.0
yarn add @tablecheck/tablekit-core@3.0.6-canary.234.9398313390.0
yarn add @tablecheck/tablekit-css@3.0.6-canary.234.9398313390.0
yarn add @tablecheck/tablekit-react@3.0.10-canary.234.9398313390.0 …
```
=> fix(tablekit-react-select): update various visuals

system/core/src/components/IconButton.ts, system/core/src/components/InputWithIcons.ts, system/core/src/components/TextAreaCore.ts, system/core/src/components/TextAreaWithIcons.ts
Discovered `lh` units can be about as widely used as the `content` resizing, so just add that in so it "progressively enhances" the textbox when the browser can.
<details>
<br />
```bash
npm install @tablecheck/tablekit-core@3.1.0-canary.238.10279101719.0
npm install @tablecheck/tablekit-css@3.1.0-canary.238.10279101719.0
npm install @tablecheck/tablekit-react@3.1.0-canary.238.10279101719.0
npm install @tablecheck/tablekit-react-css@3.1.0-canary.238.10279101719.0
npm install @tablecheck/tablekit-react-datepicker@3.1.0-canary.238.10279101719.0
npm install @tablecheck/tablekit-react-select@3.1.0-canary.238.10279101719.0
yarn add …
```
=> feat: add textarea min-lines

.gitignore, system/core/src/components/ButtonGroup.ts
Issue:
<details>
<br />
```bash
npm install @tablecheck/tablekit-core@3.1.1-canary.239.11270814258.0
npm install @tablecheck/tablekit-css@3.1.1-canary.239.11270814258.0
npm install @tablecheck/tablekit-react@3.1.1-canary.239.11270814258.0
npm install @tablecheck/tablekit-react-css@3.1.1-canary.239.11270814258.0
npm install @tablecheck/tablekit-react-datepicker@3.1.1-canary.239.11270814258.0
npm install @tablecheck/tablekit-react-select@3.1.1-canary.239.11270814258.0
yarn add @tablecheck/tablekit-core@3.1.1-canary.239.11270814258.0
yarn add @tablecheck/tablekit-css@3.1.1-canary.239.11270814258.0
yarn add @tablecheck/tablekit-react@3.1.1-canary.239.11270814258.0
yarn …
```
=> fix: fix button group rtl styles

system/core/src/components/InputWithIcons.ts, system/core/src/components/InputWithPrefix.ts, system/core/src/components/TextAreaWithIcons.ts, system/core/src/components/TextAreaWithPrefix.ts, system/stories/src/DatePicker/storyStyles.ts
Issue:
<details>
<br />
```bash
npm install @tablecheck/tablekit-core@3.1.2-canary.241.11289060743.0
npm install @tablecheck/tablekit-css@3.1.2-canary.241.11289060743.0
npm install @tablecheck/tablekit-react@3.1.2-canary.241.11289060743.0
npm install @tablecheck/tablekit-react-css@3.1.2-canary.241.11289060743.0
npm install @tablecheck/tablekit-react-datepicker@3.1.2-canary.241.11289060743.0
npm install @tablecheck/tablekit-react-select@3.1.2-canary.241.11289060743.0
yarn add @tablecheck/tablekit-core@3.1.2-canary.241.11289060743.0
yarn add @tablecheck/tablekit-css@3.1.2-canary.241.11289060743.0
yarn add @tablecheck/tablekit-react@3.1.2-canary.241.11289060743.0
yarn …
```
=> fix: rtl issues

system/react-datepicker/src/Header/MonthArrowButtons.tsx
<details>
<br />
```bash
npm install @tablecheck/tablekit-core@3.1.3-canary.242.11367434948.0
npm install @tablecheck/tablekit-css@3.1.3-canary.242.11367434948.0
npm install @tablecheck/tablekit-react@3.1.3-canary.242.11367434948.0
npm install @tablecheck/tablekit-react-css@3.1.3-canary.242.11367434948.0
npm install @tablecheck/tablekit-react-datepicker@3.1.3-canary.242.11367434948.0
npm install @tablecheck/tablekit-react-select@3.1.3-canary.242.11367434948.0
yarn add @tablecheck/tablekit-core@3.1.3-canary.242.11367434948.0
yarn add @tablecheck/tablekit-css@3.1.3-canary.242.11367434948.0
yarn add @tablecheck/tablekit-react@3.1.3-canary.242.11367434948.0
yarn add …
```
=> fix(tablekit-react-datepicker): rtl issues

system/react-css/src/utils.tsx
Corrects merging of both parent and passed component props, and supports not passing fixedProps at all
<details>
<br />
```bash
npm install @tablecheck/tablekit-core@4.1.2-canary.247.12171589848.0
npm install @tablecheck/tablekit-css@4.1.2-canary.247.12171589848.0
npm install @tablecheck/tablekit-react@4.1.2-canary.247.12171589848.0
npm install @tablecheck/tablekit-react-css@4.1.2-canary.247.12171589848.0
npm install @tablecheck/tablekit-react-datepicker@4.1.2-canary.247.12171589848.0
npm install @tablecheck/tablekit-react-select@4.1.2-canary.247.12171589848.0
yarn add @tablecheck/tablekit-core@4.1.2-canary.247.12171589848.0
yarn add …
```
=> fix: typescript definition of withComponent

system/core/src/components/TabButton.ts
For easy integration with 3rd party libraries that often add `active` class when a link is "active".
Particularly [RRv6](https://reactrouter.com/6.28.1/components/nav-link)+ upgrade where v7 doesn't specify if aria props are used or not.
<details>
<br />
```bash
npm install @tablecheck/tablekit-core@4.1.2-canary.248.12782190806.0
npm install @tablecheck/tablekit-css@4.1.2-canary.248.12782190806.0
npm install @tablecheck/tablekit-react@4.1.2-canary.248.12782190806.0
npm install @tablecheck/tablekit-react-css@4.1.3-canary.248.12782190806.0
npm install @tablecheck/tablekit-react-datepicker@4.1.2-canary.248.12782190806.0
npm install …
```
=> fix: add .active selector to tabs

system/core/src/utils/typography.ts
This allows overriding of the font-size and line-height easily for application specific values. eg `—tk-body-1-line-height: 20px`
<details>
<br />
```bash
npm install @tablecheck/tablekit-core@4.1.3-canary.249.12800567356.0
npm install @tablecheck/tablekit-css@4.1.3-canary.249.12800567356.0
npm install @tablecheck/tablekit-react@4.1.3-canary.249.12800567356.0
npm install @tablecheck/tablekit-react-css@4.1.4-canary.249.12800567356.0
npm install @tablecheck/tablekit-react-datepicker@4.1.3-canary.249.12800567356.0
npm install @tablecheck/tablekit-react-select@4.1.3-canary.249.12800567356.0
yarn add @tablecheck/tablekit-core@4.1.3-canary.249.12800567356.0
yarn add …
```
=> feat: add more CSS vars for typography

system/core/src/components/Checkbox.ts
Misaligned indeterminate styling - `background-attachment: center` is not valid (not sure when that got deprecated)
<details>
<br />
```bash
npm install @tablecheck/tablekit-core@4.1.4-canary.250.13232447551.0
npm install @tablecheck/tablekit-css@4.1.4-canary.250.13232447551.0
npm install @tablecheck/tablekit-react@4.1.4-canary.250.13232447551.0
npm install @tablecheck/tablekit-react-css@4.1.5-canary.250.13232447551.0
npm install @tablecheck/tablekit-react-datepicker@4.1.4-canary.250.13232447551.0
npm install @tablecheck/tablekit-react-select@4.1.4-canary.250.13232447551.0
yarn add @tablecheck/tablekit-core@4.1.4-canary.250.13232447551.0
yarn add …
```
=> fix: checkbox indeterminate styling

system/core/src/components/TextAreaCore.ts, system/stories/src/TextArea.stories.tsx
Related to [MOPS-2995](https://tablecheck.atlassian.net/browse/MOPS-2995).
[MOPS-2995]: https://tablecheck.atlassian.net/browse/MOPS-2995?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
<details>
<br />
```bash
npm install @tablecheck/tablekit-core@4.1.5-canary.251.13673585486.0
npm install @tablecheck/tablekit-css@4.1.5-canary.251.13673585486.0
npm install @tablecheck/tablekit-react@4.1.5-canary.251.13673585486.0
npm install @tablecheck/tablekit-react-css@4.1.6-canary.251.13673585486.0
npm install @tablecheck/tablekit-react-datepicker@4.1.5-canary.251.13673585486.0
npm install …
```
=> fix: textarea overflow
